[package]
name = "poirot"
version = "1.0.0"
authors = ["vedran <vinkovedran@gmail.com>"]
edition = "2018"

[dependencies]
cursive = "0.16.3"
reqwest = "0.11.0"
tokio = { version = "1.1.1", features = ["full"] }

[profile.release]
codegen-units = 1
lto = true
opt-level = 'z'
panic = 'abort'
